### ISSUE TITLE
Remove dependency on HostBuilders

### ISSUE THREAD

**Issue by Wautvda** [leonibr/community-extensions-cache-postgres#28]
The DI wiring of this nuget through `AddDistributedPostgreSqlCache` depends on the registration of `IHostApplicationLifetime` for the `DatabaseExpiredItemsRemoverLoop`.
This is usefull when registering applications through the hostbuilder.
We are also depending on AWS lambdas which don't have the luxury of hostbuilders (unfortunately) and therefor lacking `IHostApplicationLifetime`. A solution could be an optional dependency to inject.

**Comment by leonibr** [comment]
try it version 3.1.2, and let me know,

**Comment by Wautvda** [comment]
Seems to be working for us, thanks! Next time I'll make a PR. But nice job!
