### ISSUE TITLE
Irrelevant README's description

### ISSUE THREAD

**Issue by Jenevra** [leonibr/community-extensions-cache-postgres#7]
Hi :)

I suppose that the description of your README document is a bit irrelevant.

It concerns this part (point 2):
```
services.AddDistributedPostgreSqlCache(setup => 
{
	ConnectionString = configuration["ConnectionString"], 
	SchemaName = configuration["SchemaName"],
	TableName = configuration["TableName"],
	RemoveExpiredDisabled = configuration["RemoveExpiredDisabled"],
    // Optional - RemoveExpiredDisabled default is FALSE
	CreateInfrastructure = configuration["CreateInfrastructure"] 
	// CreateInfrastructure is optional, default is TRUE
	// This means que every time starts the application the 
	// creation of table and database functions will be verified.
})
```

First of all, this parameter `RemoveExpiredDisabled` doesn't exist anymore. I guess now it's called `DisableRemoveExpired`. 
Also, the way it's all written is incorrect - need to add `setup.` before every parameter or `new PostgreSqlCacheOptions()` is missing.

**Comment by leonibr** [comment]
Hi,  Thank you for pointing that out!

**Comment by leonibr** [comment]
@Jenevra  could you please checkout branch  `fix#7`, anything more you would like to add?

**Comment by Jenevra** [comment]
Oh, yeah, you also need to put `;` instead of `,` after each row (sorry, forgot to mention it). 
And, I think, that's all)

**Comment by leonibr** [comment]
done, thanks
