### ISSUE TITLE
Create a new schema when creating DB infrastructure

### ISSUE THREAD

**Issue by Jenevra** [leonibr/community-extensions-cache-postgres#9]
Hi!

What do you think about creating a schema if it does not exist in a database? It would be very useful when you set `true` for the `CreateInfrastructure` parameter, and the specified schema will be created too.

**Comment by leonibr** [comment]
Sorry for the delay, @Jenevra !
You are absolutely right 😊
I don't know why this is not the set along side the rest of infrastructure creation!!, thanks for point that out!
